/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package focusmind;

import java.awt.Color;
import java.awt.Window;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;

/**
 *
 * @author user
 */
public class DuplicatedTaskPanel extends javax.swing.JPanel {
    public boolean ignore_pressed = false;
    public boolean change_pressed = false;
    private String new_name = null;
    /**
     * Creates new form DuplicatedTaskPanel
     */
    public DuplicatedTaskPanel() {
        initComponents();
        this.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 2));
    }
    public void setTaskName(String name){
        this.LabelTaskName.setText(name);
    }
    public void reset_options(){
        ignore_pressed = false;
        change_pressed = false;
        new_name = null;
    }
    private void close(){
        Window window = SwingUtilities.getWindowAncestor(this);
        if (window instanceof JDialog currentDialog) {
            currentDialog.dispose();
        }
    }
    public void ignore(){
        ignore_pressed = true;
        Options.getInstance().setIGNORE_DUPLICATED_NAMES(true);
        close();
    }
    public void change(){
        change_pressed = true;
        this.new_name = this.InputNewName.getText();
        close();
    }
    public String getNewName(){
        return this.new_name;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LabelTaskName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InputNewName = new javax.swing.JTextField();
        ButtonChangeName = new javax.swing.JButton();
        ButtonIgnoreAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setText("Ya existe una tarea con el nombre: ");

        LabelTaskName.setText("[TaskName]");

        jLabel2.setText("Nuevo nombre (opcional):");

        ButtonChangeName.setText("Cambiar nombre");
        ButtonChangeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonChangeNameActionPerformed(evt);
            }
        });

        ButtonIgnoreAll.setText("Ignorar todos");
        ButtonIgnoreAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIgnoreAllActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(242, 242, 242));
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Si se elige la opción \"ignorar todos\", se cambiaran automaticamente los nombres y la configuración persistirá, para cambiarla hacerlo en la configuración.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTaskName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(InputNewName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(ButtonIgnoreAll, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(ButtonChangeName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LabelTaskName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InputNewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonIgnoreAll, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonChangeName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonIgnoreAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIgnoreAllActionPerformed
        ignore();
    }//GEN-LAST:event_ButtonIgnoreAllActionPerformed

    private void ButtonChangeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonChangeNameActionPerformed
        change();
    }//GEN-LAST:event_ButtonChangeNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonChangeName;
    private javax.swing.JButton ButtonIgnoreAll;
    private javax.swing.JTextField InputNewName;
    private javax.swing.JLabel LabelTaskName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
