package focusmind;

import javax.swing.JOptionPane;

public class OptionsView extends javax.swing.JFrame {

    public OptionsView() {
        initComponents();
        String filename = Options.getInstance().getCALENDAR_FILE_NAME();
        filename = filename.split("\\.")[0];
        this.InputCalendarFileName.setText(filename);
        this.InputMaxIterations.setText(Integer.toString(Options.getInstance().getMAX_ITERATIONS()));
        this.InputMaxStudyIterations.setText(Integer.toString(Options.getInstance().getMAX_STUDY_ITERATIONS()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        InputCalendarFileName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InputMaxStudyIterations = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InputMaxIterations = new javax.swing.JTextField();
        ButtonSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre de la base de datos:");

        InputCalendarFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCalendarFileNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Máximo de iteraciones por día:");

        jLabel3.setText("Máximo de iteraciones en el calendario:");

        ButtonSave.setText("Guardar");
        ButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel4.setText("CONFIGURACIONES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(InputCalendarFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(InputMaxStudyIterations)
                            .addComponent(InputMaxIterations)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(ButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(InputCalendarFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InputMaxStudyIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(InputMaxIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputCalendarFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCalendarFileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCalendarFileNameActionPerformed

    private void ButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveActionPerformed
        boolean save = true;
        String errorIn = "";
        String calendarFileName = null;
        if(!this.InputCalendarFileName.getText().isBlank()){
            calendarFileName = this.InputCalendarFileName.getText();
        }else{
            save = false;
            errorIn += " Calendar file name.";
        }
        int maxStudyIterations = 0;
        if(!this.InputMaxStudyIterations.getText().isBlank()){
            try{
                maxStudyIterations = Integer.parseInt(this.InputMaxStudyIterations.getText());
            }catch(NumberFormatException e){
                save = false;
                errorIn += " Max iterations per day.";
            }
        }else{
            save = false;
            errorIn += " Max iterations per day.";
        }
        int maxIterations = 0;
        if(!this.InputMaxIterations.getText().isBlank()){
            try{
                maxIterations = Integer.parseInt(this.InputMaxIterations.getText());
            }catch(NumberFormatException e){
                save = false;
                errorIn += " Max iterations in all time.";
            }
        }else{
            save = false;
            errorIn += " Max iterations in all time.";
        }
        if(save){
            Options op = Options.getInstance();
            calendarFileName = calendarFileName.split("\\.")[0];
            calendarFileName = calendarFileName+".txt";
            op.setCALENDAR_FILE_NAME(calendarFileName);
            op.setMAX_ITERATIONS(maxIterations);
            op.setMAX_STUDY_ITERATIONS(maxStudyIterations);
            int null_iteration = maxIterations+1;
            op.setNULL_ITERATION(null_iteration);
            MainView mv = new MainView();
            mv.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Usted tiene errores en los campos:"+errorIn, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSave;
    private javax.swing.JTextField InputCalendarFileName;
    private javax.swing.JTextField InputMaxIterations;
    private javax.swing.JTextField InputMaxStudyIterations;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
