package focusmind;

import java.io.File;
import javax.swing.JOptionPane;

public class OptionsView extends javax.swing.JFrame {
    private boolean ignore_duplicates;
    public OptionsView() {
        initComponents();
        this.setLocationRelativeTo(null);
        String filename = Options.getInstance().getCALENDAR_FILE_NAME();
        filename = filename.split("\\.")[0];
        this.InputCalendarFileName.setText(filename);
        this.InputMaxIterations.setText(Integer.toString(Options.getInstance().getMAX_ITERATIONS()));
        this.InputMaxStudyIterations.setText(Integer.toString(Options.getInstance().getMAX_STUDY_ITERATIONS()));
        this.ignore_duplicates = Options.getInstance().getIGNORE_DUPLICATED_NAMES();
        this.toggleButtonIDN();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        InputCalendarFileName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        InputMaxStudyIterations = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InputMaxIterations = new javax.swing.JTextField();
        ButtonSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ButtonClose = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TButtonIgnoreDuplicated = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre de la base de datos:");

        InputCalendarFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCalendarFileNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Máximo de iteraciones por día:");

        jLabel3.setText("Máximo de iteraciones en el calendario:");

        ButtonSave.setText("Guardar");
        ButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel4.setText("CONFIGURACIONES");

        ButtonClose.setText("<");
        ButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCloseActionPerformed(evt);
            }
        });

        jLabel5.setText("Ignorar duplicados (nombre automatico):");

        TButtonIgnoreDuplicated.setText("No");
        TButtonIgnoreDuplicated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TButtonIgnoreDuplicatedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(ButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(ButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(InputCalendarFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(InputMaxStudyIterations)
                    .addComponent(InputMaxIterations)
                    .addComponent(TButtonIgnoreDuplicated, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(ButtonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(InputCalendarFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InputMaxStudyIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(InputMaxIterations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TButtonIgnoreDuplicated))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(ButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputCalendarFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCalendarFileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCalendarFileNameActionPerformed

    private void ButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSaveActionPerformed
        boolean save = true;
        String errorIn = "";
        String calendarFileName = null;
        if(!this.InputCalendarFileName.getText().isBlank()){
            calendarFileName = this.InputCalendarFileName.getText();
        }else{
            save = false;
            errorIn += " Calendar file name.";
        }
        int maxStudyIterations = 0;
        if(!this.InputMaxStudyIterations.getText().isBlank()){
            try{
                maxStudyIterations = Integer.parseInt(this.InputMaxStudyIterations.getText());
            }catch(NumberFormatException e){
                save = false;
                errorIn += " Max iterations per day.";
            }
        }else{
            save = false;
            errorIn += " Max iterations per day.";
        }
        int maxIterations = 0;
        if(!this.InputMaxIterations.getText().isBlank()){
            try{
                maxIterations = Integer.parseInt(this.InputMaxIterations.getText());
            }catch(NumberFormatException e){
                save = false;
                errorIn += " Max iterations in all time.";
            }
        }else{
            save = false;
            errorIn += " Max iterations in all time.";
        }
        if(save){
            Options op = Options.getInstance();
            calendarFileName = calendarFileName.split("\\.")[0];
            calendarFileName = calendarFileName+".txt";
            String old_file_name = op.getCALENDAR_FILE_NAME();
            op.setCALENDAR_FILE_NAME(calendarFileName);
            ConfigFileManager.getInstance().set(Options.calendar_file_name_var_name, calendarFileName);
            op.setMAX_ITERATIONS(maxIterations);
            ConfigFileManager.getInstance().set(Options.max_iterations_var_name, Integer.toString(maxIterations));
            op.setMAX_STUDY_ITERATIONS(maxStudyIterations);
            ConfigFileManager.getInstance().set(Options.max_study_iterations_var_name, Integer.toString(maxStudyIterations));
            int null_iteration = maxIterations+1;
            op.setNULL_ITERATION(null_iteration);
            ConfigFileManager.getInstance().set(Options.null_iterator_var_name, Integer.toString(null_iteration));
            ConfigFileManager.getInstance().set(Options.ignore_duplicated_names_var_name, ignore_duplicates ? "1":"0");
            
            CalendarManager cm = new CalendarManager();
            
            String actualRoute = System.getProperty("user.dir");
            File old_file = new File(actualRoute+"/"+old_file_name);
            if(old_file.exists() && old_file.canRead()){
                cm.importFile(old_file, this);
            }
            if(!old_file.delete()){
                System.out.println("FocusMind can't delete the old calendar file");
            }
            
            MainView mv = new MainView();
            mv.setVisible(true);
            this.setVisible(false);
            this.dispose();
        }else{
            JOptionPane.showInputDialog(null, "Usted tiene errores en los campos:"+errorIn, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonSaveActionPerformed

    private void ButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCloseActionPerformed
        MainView mv = new MainView();
        mv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonCloseActionPerformed

    private void TButtonIgnoreDuplicatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TButtonIgnoreDuplicatedActionPerformed
        toggleButtonIDN();
    }//GEN-LAST:event_TButtonIgnoreDuplicatedActionPerformed
    
    private void toggleButtonIDN(){
        ignore_duplicates = !ignore_duplicates;
        if(ignore_duplicates){
            this.TButtonIgnoreDuplicated.setText("Si");
        }else{
            this.TButtonIgnoreDuplicated.setText("No");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClose;
    private javax.swing.JButton ButtonSave;
    private javax.swing.JTextField InputCalendarFileName;
    private javax.swing.JTextField InputMaxIterations;
    private javax.swing.JTextField InputMaxStudyIterations;
    private javax.swing.JToggleButton TButtonIgnoreDuplicated;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
